// Code generated by hero.
// source: C:\work\src\github.com\kennhung\ftcScoring\webTemplate\match_review.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/kennhung/ftcScoring/model"
)

func Match_Review(eventSettings *model.EventSettings, allMatchs [3][]model.Match, currentMatch *model.Match, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="/res/css/bootstrap.min.css" rel="stylesheet">
    <link href="/res/open-iconic/font/css/open-iconic-bootstrap.min.css" rel="stylesheet">
    <link href="/res/css/ftcScoring.css" rel="stylesheet">
    <!-- JS Scripts -->

    <!-- load jQuery 1.11.0 -->
    <script src="/res/js/jquery_v1.11.0.min.js"></script>
    <script src="/res/js/jquery.websocket-0.0.1.js"></script>
    <script src="/res/js/jquery.json-2.4.min.js"></script>
    <script src="/res/js/page_scripts/ScoringWebsocket.js"></script>
    <script type="text/javascript">
        $jQuery_1_11_0 = $.noConflict(true);
    </script>

    <script src="/res/js/jquery-3.2.1.slim.min.js"></script>
    <script src="/res/js/popper.min.js"></script>
    <script src="/res/js/bootstrap.min.js"></script>
    <script src="/res/js/bootstrap-number-input.js"></script>
    <!-- Scoring System Script -->
    <script src="/res/js/ftcScoring.js"></script>

    `)

	buffer.WriteString(`

    <title>`)
	buffer.WriteString(`
Match Review
`)

	buffer.WriteString(`- FTC Scoring</title>
</head>
<body style="padding-top: 70px;">
<div style="margin-bottom: 20px;">
    <nav class="navbar fixed-top  navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">FTC Scoring</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto" id="navbar-menu">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSetup" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Setup
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="/setup/settings">Event Settings</a>
                            <a class="dropdown-item" href="/setup/teams">Teams</a>
                            <a class="dropdown-item" href="/setup/schedule">Matches</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMatch" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Match
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="/match/play">Play</a>
                            <a class="dropdown-item" href="/match/scoring">Scoring</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="container-fluid">
    `)
	buffer.WriteString(`
<div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg">
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="practiceNav" data-toggle="tab" href="#practice" role="tab"
                   aria-controls="nav-practice" aria-selected="true">Home</a>
                <a class="nav-item nav-link" id="qualificationNav" data-toggle="tab" href="#qualification" role="tab"
                   aria-controls="nav-qualification" aria-selected="false">Qualification</a>
                <a class="nav-item nav-link" id="eliminationNav" data-toggle="tab" href="#elimination" role="tab"
                   aria-controls="nav-elimination" aria-selected="false">Playoff</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="practice" role="tabpanel" aria-labelledby="nav-practice-tab">
                `)
	Match_Play_ListTeams(allMatchs[0], currentMatch, 1, buffer)
	buffer.WriteString(`
            </div>
            <div class="tab-pane fade" id="qualification" role="tabpanel" aria-labelledby="nav-qualification-tab">
                `)
	Match_Play_ListTeams(allMatchs[1], currentMatch, 1, buffer)
	buffer.WriteString(`
            </div>
            <div class="tab-pane fade" id="elimination" role="tabpanel" aria-labelledby="nav-elimination-tab">
                `)
	Match_Play_ListTeams(allMatchs[2], currentMatch, 1, buffer)
	buffer.WriteString(`
            </div>
        </div>
    </div>
</div>


`)

	buffer.WriteString(`
</div>
</body>
</html>`)

}
