CREATE TABLE matches (
  id              INTEGER PRIMARY KEY,
  type            VARCHAR(16),
  time            DATETIME,
  red1            INT,
  red1notshow     bool,
  red1yellowCard  bool,
  red1redCard     bool,
  red2            INT,
  red2notshow     bool,
  red2yellowCard  bool,
  red2redCard     bool,
  blue1           INT,
  blue1notshow    bool,
  blue1yellowCard bool,
  blue1redCard    bool,
  blue2           INT,
  blue2notshow    bool,
  blue2yellowCard bool,
  blue21redCard   bool,
  status          VARCHAR(16),
  startedat       DATETIME,
  winner          VARCHAR(16)
);